name: "asr_am_BN"
default_model_filename: "model_BN.plan"
platform: "tensorrt_plan"

max_batch_size: 1

input [
      {
        name: "audio_signal"
        data_type: TYPE_FP32
        dims: [80, -1]
        is_shape_tensor: false
      },
      
      {
        name: "length"
        data_type: TYPE_INT32
        reshape: {shape: []}
        dims: [1]
        is_shape_tensor: false
      }
]

output [
      {
        name: "logprobs"
        data_type: TYPE_FP32
        is_shape_tensor: false
        dims: [-1,5633]
      }
]

  
instance_group [
    { 
    count: 1
    kind: KIND_GPU
    profile: ["0"]
    }
]

