name: "asr_conversion"
backend: "python"
max_batch_size: 1

input [
  {
    name: "input"
    data_type: TYPE_INT64
    dims: [1]
    reshape : {shape:[]}
  }
]

output [
  {
    name: "output"
    data_type: TYPE_INT32
    dims: [ 1]
    reshape : {shape:[]}
  }
]

instance_group [
  {
    count: 1
    kind: KIND_CPU
  }
]