name: "entity_GU"
backend: "python"
max_batch_size: 1
input [
{
    name: "input_text"
    data_type: TYPE_STRING
    dims: [ 1 ]
    reshape: {shape:[]}
},
{
    name: "input_text_itn"
    data_type: TYPE_STRING
    dims: [ 1 ]
    optional: true
    reshape: {shape:[]}
}
]
output {
    name: "entities"
    data_type: TYPE_STRING
    dims: [ 1 ]
}

  
instance_group [
    { 
    count: 1
    kind: KIND_CPU 
    }
]

